name: Deploy to BCR

on:
  push:
    tags:
      - "*"

jobs:
  balena-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update balena.yml
        uses: balena-io-experimental/balena.yml-action@main
        with:
          sync_readme: true
          sync_tag: true

      - name: balena CLI Action
        uses: balena-community/community-cli-action@1.0.0
        with:
          balena_token: ${{secrets.BALENA_TOKEN}}
          balena_cli_commands: >
            push maggie0002/plex-seedbox;
          balena_cli_version: 13.7.1
